from tkinter import *
mw=Tk()
mw.title("Student Registration Form")
mw.geometry("500x500")
Label(mw,text="Name:",fg="Red").grid(row=0,column=0)
Entry(mw,width=20).grid(row=0,column=1)
Label(mw,text="Roll No:",fg="Red").grid(row=1,column=0)
Entry(mw,width=20).grid(row=1,column=1)
Label(mw,text="Branch:").grid(row=2,column=0)
C1=Checkbutton(mw,text="AI&ML")
C1.grid(row=3,column=0)
C2=Checkbutton(mw,text="CSE")
C2.grid(row=4,column=0)
Label(mw,text="PROGRAMMING LANGUAGES",fg="Blue").grid(row=5,column=0)
LB=Listbox(mw,height=3)
LB.insert(1,"JAVA")
LB.insert(2,"PYTHON")
LB.insert(3,"C++")
LB.grid(row=6,column=0)
Radiobutton(mw,text="Male",value=1).grid(row=7,column=0)
Radiobutton(mw,text="Female",value=2).grid(row=8,column=0)
Button(mw,text="SUBMIT").grid(row=9,column=0)
mw.mainloop()
